### ISSUE TITLE
ModuleNotFoundError: No module named 'console'

### ISSUE THREAD

**Issue by jacklenox** [dawsonbooth/ascii-art#1]
Hello, when I try to run this program I get the following error:

```
Traceback (most recent call last):
  File "/home/jack/.local/bin/ascii-art", line 5, in <module>
    from console import main
ModuleNotFoundError: No module named 'console'
```

**Comment by dawsonbooth** [comment]
Looks like I didn't include the console script correctly. This should be fixed in the latest version, [v1.1.0](https://pypi.org/project/ascii-art-cli/1.1.0/). Let me know if there are any problems!
